### ISSUE TITLE
Create a Preview Feature

### ISSUE THREAD

**Issue by ammaaraslam** [ammaaraslam/tweetsnap#2]
**The feature**
Create a button above the download button to preview the output image before downloading

**How to implement:**
- [ ] Create a button above the downloads button
- [ ] Create an onClick function to the button that opens a modal
- [ ] Display the output image of the tweet inside that modal

**Submit your build**
- [ ] Create a new branch `preview-feature-[yourname]`
- [ ] Create a new pull request
- [ ] Wait for review

**Comment by swapn652** [comment]
Isn't the image on the left side a preview?

**Comment by ammaaraslam** [comment]
The image on the left is just a div_(component)_ and **not the actual scale and resolution** of the image that is downloaded. So the preview feature is to be implemented so that the user can see the actual result/output before downloading.

Therefore, the preview feature is to display a modal that contains the output of the **Download button** instead of actually downloading the image.
