### ISSUE TITLE
Certain parts of downloaded images look distorted

### ISSUE THREAD

**Issue by swapn652** [ammaaraslam/tweetsnap#5]
**Describe the bug**
Downloaded image looks distorted in all the three formats, jpg, png and svg. It looks fine on the website. The problem occurs only after downloading the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/70851202/175966698-dc5b5264-9d73-47c7-a21a-dc5946c471b3.png)
![image](https://user-images.githubusercontent.com/70851202/175966762-8c24547b-15ce-486c-8da1-5b7cb1c26d31.png)
![image](https://user-images.githubusercontent.com/70851202/175966823-c463b787-69a6-4c7a-947b-47230f2bf3e9.png)
![image](https://user-images.githubusercontent.com/70851202/175967224-a3b9ed6a-a91b-41b8-b8f3-eb67e525da43.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge

**Comment by ammaaraslam** [comment]
Hey @swapn652. Thanks for pointing out another bug. I've had some time to reproduce the bug, and it appears that only certain tweets are having this issue.
Nevertheless, it is a bug that needs to be fixed right away. My guess would be that the issue has to do with the settings for the [`dom-to-image`](https://github.com/tsayen/dom-to-image)  library.
Anyone willing to fix this bug feel free to let me know👇
