### ISSUE TITLE
Bug in downloaded image

### ISSUE THREAD

**Issue by ashrafchowdury** [ammaaraslam/tweetsnap#6]
Hey, Ammaaraslam 👋

I found a bug in the downloaded image. When I downloaded the photo, it was downloaded half like this 👇

I try to fix this issue, but I can't run this project in the local environment.

![image](https://user-images.githubusercontent.com/87828904/202384094-3ba6eb0a-33d0-4a6f-aef7-06425c29c891.png)

**Comment by ammaaraslam** [comment]
Hi @ashrafchowdury 
Thanks for creating the issue. If you'd like to work on the issue I can help you out to run the project in your local machine

**Comment by ashrafchowdury** [comment]
> Hi @ashrafchowdury Thanks for creating the issue. If you'd like to work on the issue I can help you out to run the project in your local machine

Hey @ammaaraslam, I'm interested in working on this project. ❤

**Comment by ammaaraslam** [comment]
> > Hi @ashrafchowdury Thanks for creating the issue. If you'd like to work on the issue I can help you out to run the project in your local machine
> 
> Hey @ammaaraslam, I'm interested in working on this project. ❤

That's amazing @ashrafchowdury!
Let me know the issue you're having when running the project locally

**Comment by ashrafchowdury** [comment]
I got this Unauthorized warning when I tried to submit any tweet link. 👇

![image](https://user-images.githubusercontent.com/87828904/202652172-f9bf6a72-2d91-4639-963e-c697e25ecc66.png)

**Comment by ammaaraslam** [comment]
> I got this Unauthorized warning when I tried to submit any tweet link. 👇
> 
> ![image](https://user-images.githubusercontent.com/87828904/202652172-f9bf6a72-2d91-4639-963e-c697e25ecc66.png)

Did you add in your Twitter with key to the environment variable? If not, refer the 4th step in the README.md under Development

**Comment by ashrafchowdury** [comment]
Hey @ammaaraslam, I fixed this problem. Check it out in the pull request section.
